stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: papango/composer
      registry: 127.0.0.1:34665
timeout: 60
notification: {}
